site_name: Top secret documentation
repo_url: https://github.com/edvm/secrets-py.git
site_url: https://github.com/edvm/secrets-py.git
site_description: topsecret
site_author: Emiliano Dalla Verde Marcozzi 
edit_uri: edit/main/docs/
repo_name: edvm/secrets-py
copyright: Maintained by <a href="https://github.com/edvm/">edvm</a>.

nav:
  - Home: index.md
  - Encryption:
    - AES cipher: infra/cipher/aes.md
    - Encryption service: services/encryption.md 
  - Storage:
    - In memory (for dev): infra/storage/inmem.md
  - Delivery:
    - Rest API: adapters/webapi.md

docs_dir: docs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["topsecret"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/edvm/topsecret
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/topsecret

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
